### ISSUE TITLE
Edge Workflow failed - cannot find publish button

### ISSUE THREAD

**Issue by roedesh** [plasmo-corp/bpp#29]
Hi @louisgv,

After your contribution to Copy Guard, I tried the submit workflow, but it only managed to submit to the Chrome and Edge store.

It fails with this error:

```
a: waiting for selector `#publishButton` failed: timeout 30000ms exceeded
    at new d (/home/runner/work/_actions/plasmo-corp/bpp/v1/dist/index.js:36:35640)
    at waitForSelectorInPage (/home/runner/work/_actions/plasmo-corp/bpp/v1/dist/index.js:36:33752)
    at Object.A.queryOne.u.waitFor (/home/runner/work/_actions/plasmo-corp/bpp/v1/dist/index.js:[23](https://github.com/roedesh/copyguard/runs/5338858177?check_suite_focus=true#step:6:23):67036)
    at waitForSelector (/home/runner/work/_actions/plasmo-corp/bpp/v1/dist/index.js:36:31998)
    at A.waitForSelector (/home/runner/work/_actions/plasmo-corp/bpp/v1/dist/index.js:36:47436)
    at B.waitForSelector (/home/runner/work/_actions/plasmo-corp/bpp/v1/dist/index.js:36:99750)
    at /home/runner/work/_actions/plasmo-corp/bpp/v1/dist/index.js:169:9097
    at Generator.next (<anonymous>)
    at /home/runner/work/_actions/plasmo-corp/bpp/v1/dist/index.js:8:2[30](https://github.com/roedesh/copyguard/runs/5338858177?check_suite_focus=true#step:6:30)9
    at new Promise (<anonymous>)
```

I also get this server response error: `Server response: Duplicate add-on ID found. (status: 400)`

**Comment by louisgv** [comment]
@roedesh I'm on it! 

> ```
> a: waiting for selector `#publishButton` failed: timeout 30000ms exceeded
>     at new d (/home/runner/work/_actions/plasmo-corp/bpp/v1/dist/index.js:36:35640)
>     at waitForSelectorInPage (/home/runner/work/_actions/plasmo-corp/bpp/v1/dist/index.js:36:33752)
>     at Object.A.queryOne.u.waitFor (/home/runner/work/_actions/plasmo-corp/bpp/v1/dist/index.js:[23](https://github.com/roedesh/copyguard/runs/5338858177?check_suite_focus=true#step:6:23):67036)
>     at waitForSelector (/home/runner/work/_actions/plasmo-corp/bpp/v1/dist/index.js:36:31998)
>     at A.waitForSelector (/home/runner/work/_actions/plasmo-corp/bpp/v1/dist/index.js:36:47436)
>     at B.waitForSelector (/home/runner/work/_actions/plasmo-corp/bpp/v1/dist/index.js:36:99750)
>     at /home/runner/work/_actions/plasmo-corp/bpp/v1/dist/index.js:169:9097
>     at Generator.next (<anonymous>)
>     at /home/runner/work/_actions/plasmo-corp/bpp/v1/dist/index.js:8:2[30](https://github.com/roedesh/copyguard/runs/5338858177?check_suite_focus=true#step:6:30)9
>     at new Promise (<anonymous>)
> ```

This is weird, can you double check to see if Edge store was actually updated? The error above only pertains to store that uses Puppeteer (temporary solution until we reverse engineer their store API or use their official API). I suspect it failed and was not able to submit at all. 
 
> I also get this server response error: `Server response: Duplicate add-on ID found. (status: 400)`

This comes from the mozilla store, let me double check. I thought I added a logic to dedupe the id if it exists in the manifest. This error occured because the manifest has an id: https://github.com/roedesh/copyguard/blob/main/dist/manifest.json#L8, and the `keys.json` also have an id.

**Comment by louisgv** [comment]
Work on this is being done here: https://github.com/plasmo-corp/bms/pull/9 <= once merged into upstream, we will proceed with updating `bpp` dependency.

So far, it seems the edge extension store has changed quite a bit compared to previous revision. Some identifier have been deprecated. 

For future implementation, using the extension submission API is probably preferred: https://docs.microsoft.com/en-us/microsoft-edge/extensions-chromium/publish/api/using-addons-api <- this API is private preview only at the moment, hopefully someone from MSFT can help giving access?

**Comment by roedesh** [comment]
The Edge store did update, the new .zip file was added, but not published yet.

For the Firefox step, I believe I tried it twice, once with and once without the "extId" parameter, and both gave the duplicate error. But I will try it again without the "extId" when I have a new version ready.
