### ISSUE TITLE
Accept edge notes field as a independent input to action

### ISSUE THREAD

**Issue by melink14** [plasmo-corp/bpp#69]
Since one purpose of the certification notes for edge is cataloging changes from previous publish it makes sense to allow setting it from an argument vs it being static as a Github secret.

It's possible that the secret could contain the static part or a template where the change notes get inserted.

**Comment by louisgv** [comment]
Will get on this sometime this weekend! Thanks so much for the FR :)

**Comment by louisgv** [comment]
nvm, #71 is ready - @melink14 Can you pls review and lmk if I missed anything
